import { sql } from 'drizzle-orm'
import type { FastifyInstance } from 'fastify'
import { z } from 'zod'

import { hashPassword, verifyPassword } from '../auth/passwords.js'
import { issueSession, revokeSession } from '../auth/sessions.js'
import { admit } from '../lib/invites.js'
import { badRequest, conflict, unauthorized } from '../lib/errors.js'
import { one } from '../lib/rows.js'
import { publicMe } from './serialize.js'

// Screen 10c asks for name, e-mail, phone and a password in one go, because it
// only appears when you are already trying to list something.
const registerBody = z.object({
  displayName: z.string().min(1).max(60),
  email: z.string().email(),
  phone: z.string().min(6).max(20).optional(),
  password: z.string().min(8, 'Passordet må ha minst 8 tegn.'),
  postalCode: z.string().regex(/^\d{4}$/).optional(),
  town: z.string().optional(),
  // The link that let you in. Spent here unless it was already spent when this
  // device started looking around.
  invite: z.string().min(16).max(64).optional(),
})

export default async function authRoutes(app: FastifyInstance) {
  /**
   * Looking around without an account.
   *
   * A device is an identity until a trade needs a stable one: you may browse and
   * wish, and the wishes are kept, so nothing is lost when the profile is made
   * on 10c. The device id is generated by the client and is the only credential
   * this account has — which is why a device that has been claimed is not let
   * back in this way. After 10c the password is the credential, and a leaked
   * device id must not be a way around it.
   */
  app.post('/auth/anonymous', async (request, reply) => {
    const body = z
      .object({ deviceId: z.string().min(16).max(200), invite: z.string().min(16).max(64).optional() })
      .parse(request.body)

    // An erased account has no device id left, so a device whose account was
    // deleted comes back here as a stranger, which is the right answer.
    const existing = await one(
      app.db,
      sql`select * from users where device_id = ${body.deviceId} and anonymised_at is null`,
    )

    if (existing?.['email']) {
      throw conflict(
        'device_claimed',
        'Denne enheten hører allerede til en konto. Logg inn med e-post og passord.',
      )
    }
    if (existing) {
      return { token: await issueSession(app.db, existing['id']), user: publicMe(existing) }
    }

    const userId = await app.db.transaction(async (tx) => {
      const rows = await tx.execute<Record<string, any>>(
        sql`insert into users (device_id) values (${body.deviceId}) returning id`,
      )
      const id = rows[0]!['id'] as string
      // Inside the transaction on purpose: if the invitation turns out to be
      // spent, the account it would have made goes away with it.
      await admit(tx, body.invite, id, app.inviteOnly)
      return id
    })

    const user = await one(app.db, sql`select * from users where id = ${userId}`)
    reply.code(201)
    return { token: await issueSession(app.db, userId), user: publicMe(user!) }
  })

  app.post('/auth/register', async (request, reply) => {
    const body = registerBody.parse(request.body)

    // Someone who has been looking around on this device keeps their row, and
    // with it every wish they have expressed. Making a profile is claiming the
    // account, not starting a second one.
    const claiming = request.userId && !request.userClaimed ? request.userId : null

    const taken = await one(
      app.db,
      // `is distinct from` rather than `<>`: with nobody being claimed the
      // comparison is against null, and `id <> null` is null, which is not false.
      sql`select 1 from users where email = ${body.email}
            and id is distinct from ${claiming}::uuid`,
    )
    if (taken) throw conflict('email_taken', 'Det finnes allerede en konto med denne e-posten.')

    const passwordHash = await hashPassword(body.password)

    const userId = await app.db.transaction(async (tx) => {
      if (claiming) {
        await tx.execute(
          sql`update users set display_name = ${body.displayName}, email = ${body.email},
                               phone = ${body.phone ?? null}, password_hash = ${passwordHash},
                               postal_code = ${body.postalCode ?? null},
                               town = coalesce(${body.town ?? null}, town)
              where id = ${claiming}`,
        )
        // The invitation was spent when this device first looked around, so a
        // second one is neither needed nor asked for.
        return claiming
      }

      const rows = await tx.execute<Record<string, any>>(
        sql`insert into users (display_name, email, phone, password_hash, postal_code, town)
            values (${body.displayName}, ${body.email}, ${body.phone ?? null},
                    ${passwordHash}, ${body.postalCode ?? null}, ${body.town ?? null})
            returning id`,
      )
      const id = rows[0]!['id'] as string
      await admit(tx, body.invite, id, app.inviteOnly)
      return id
    })

    if (claiming) {
      // Nothing to match yet: the wishes this device made only close a loop once
      // it has something to give, and listing that is the next screen. The
      // search runs there.
      //
      // The session is reissued: the account has just gained a password, and the
      // token that belonged to a device should not outlive the change.
      const header = request.headers.authorization
      if (header?.startsWith('Bearer ')) await revokeSession(app.db, header.slice(7))
    }

    const user = await one(app.db, sql`select * from users where id = ${userId}`)
    reply.code(201)
    return { token: await issueSession(app.db, userId), user: publicMe(user!) }
  })

  app.post('/auth/login', async (request) => {
    const body = z.object({ email: z.string().email(), password: z.string() }).parse(request.body)

    const user = await one(app.db, sql`select * from users where email = ${body.email}`)
    // Same answer either way: telling someone the address exists is telling them
    // half of a credential.
    if (!user?.['password_hash'] || !(await verifyPassword(body.password, user['password_hash']))) {
      throw unauthorized()
    }

    return { token: await issueSession(app.db, user['id']), user: publicMe(user) }
  })

  app.post('/auth/logout', async (request, reply) => {
    const header = request.headers.authorization
    if (header?.startsWith('Bearer ')) await revokeSession(app.db, header.slice(7))
    reply.code(204)
  })

  // BankID is confirmed at the first trade, and the app only ever learns yes or
  // no. The provider keeps the person; we keep a pseudonym. Until there is a
  // provider contract this accepts the subject it is handed.
  app.post('/me/bankid', async (request) => {
    const userId = app.requireClaimedUser(request)
    const body = z.object({ subject: z.string().min(4) }).parse(request.body)

    const clash = await one(
      app.db,
      sql`select 1 from users where bankid_subject = ${body.subject} and id <> ${userId}`,
    )
    if (clash) throw badRequest('bankid_taken', 'Denne BankID-en er allerede i bruk.')

    const user = await one(
      app.db,
      sql`update users set bankid_subject = ${body.subject}, bankid_verified_at = now()
          where id = ${userId} returning *`,
    )
    return publicMe(user!)
  })
}
