ALTER TABLE products ADD COLUMN restricted boolean NOT NULL DEFAULT false;
ALTER TABLE products ADD COLUMN revision int NOT NULL DEFAULT 1;
CREATE TABLE product_members(product_id uuid REFERENCES products(id) ON DELETE CASCADE,user_id uuid REFERENCES users(id) ON DELETE CASCADE,role text NOT NULL CHECK(role IN('editor','reader')),PRIMARY KEY(product_id,user_id));
CREATE TABLE product_history(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id) ON DELETE CASCADE,revision int NOT NULL,snapshot jsonb NOT NULL,author text NOT NULL,created_at timestamptz DEFAULT now(),UNIQUE(product_id,revision));
INSERT INTO product_history(product_id,revision,snapshot,author) SELECT id,revision,to_jsonb(products),'Migration' FROM products;
CREATE TABLE password_resets(token_hash text PRIMARY KEY,user_id uuid REFERENCES users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL,used_at timestamptz);
ALTER TABLE invites ADD COLUMN revoked_at timestamptz;
ALTER TABLE items ADD COLUMN deleted_at timestamptz;
ALTER TABLE items ADD COLUMN inbox boolean NOT NULL DEFAULT true;
ALTER TABLE items ADD COLUMN metadata jsonb NOT NULL DEFAULT '{}';
ALTER TABLE items ADD COLUMN rights_details jsonb NOT NULL DEFAULT '{}';
ALTER TABLE versions ADD COLUMN checksum text NOT NULL DEFAULT '';
ALTER TABLE versions ADD COLUMN bytes bigint NOT NULL DEFAULT 0;
ALTER TABLE versions ADD COLUMN provenance jsonb NOT NULL DEFAULT '{}';
CREATE INDEX version_checksum ON versions(checksum) WHERE checksum<>'';
ALTER TABLE notes ADD COLUMN resolved_at timestamptz;
ALTER TABLE notes ADD COLUMN mentions text[] NOT NULL DEFAULT '{}';
CREATE TABLE collections(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id) ON DELETE CASCADE,name text NOT NULL,created_at timestamptz DEFAULT now(),UNIQUE(product_id,name));
CREATE TABLE collection_items(collection_id uuid REFERENCES collections(id) ON DELETE CASCADE,item_id uuid REFERENCES items(id) ON DELETE CASCADE,PRIMARY KEY(collection_id,item_id));
CREATE TABLE favorites(user_id uuid REFERENCES users(id) ON DELETE CASCADE,item_id uuid REFERENCES items(id) ON DELETE CASCADE,PRIMARY KEY(user_id,item_id));
CREATE TABLE saved_searches(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES users(id) ON DELETE CASCADE,product_id uuid REFERENCES products(id) ON DELETE CASCADE,name text NOT NULL,query jsonb NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE relations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),source_id uuid REFERENCES items(id),target_id uuid REFERENCES items(id),kind text NOT NULL CHECK(kind IN('uses','variant','inspired_by','part_of','contradicts','supports')),version_id uuid REFERENCES versions(id),created_at timestamptz DEFAULT now(),CHECK(source_id<>target_id),UNIQUE(source_id,target_id,kind));
CREATE TABLE ratings(item_id uuid REFERENCES items(id),version_id uuid REFERENCES versions(id),user_id uuid REFERENCES users(id),value int CHECK(value IN(-1,1)),created_at timestamptz DEFAULT now(),PRIMARY KEY(version_id,user_id));
CREATE TABLE shares(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),token_hash text UNIQUE NOT NULL,version_id uuid REFERENCES versions(id),expires_at timestamptz NOT NULL,revoked_at timestamptz,created_by uuid REFERENCES users(id),created_at timestamptz DEFAULT now());
CREATE TABLE campaigns(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),name text NOT NULL,goal text NOT NULL DEFAULT '',starts_at date,ends_at date,budget numeric NOT NULL DEFAULT 0 CHECK(budget>=0),channels text[] NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'planned',created_at timestamptz DEFAULT now());
ALTER TABLE tasks ADD COLUMN campaign_id uuid REFERENCES campaigns(id);
ALTER TABLE tasks ADD COLUMN specification jsonb NOT NULL DEFAULT '{}';
ALTER TABLE tasks ADD COLUMN progress jsonb NOT NULL DEFAULT '{}';
ALTER TABLE tasks ADD COLUMN revision int NOT NULL DEFAULT 1;
ALTER TABLE tasks ADD COLUMN parent_id uuid REFERENCES tasks(id);
CREATE TABLE task_sources(task_id uuid REFERENCES tasks(id),version_id uuid REFERENCES versions(id),role text NOT NULL DEFAULT 'source',PRIMARY KEY(task_id,version_id,role));
CREATE TABLE task_deliveries(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id uuid REFERENCES tasks(id),revision int NOT NULL,version_id uuid REFERENCES versions(id),manifest jsonb NOT NULL,author text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE task_feedback(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),task_id uuid REFERENCES tasks(id),revision int NOT NULL,body text NOT NULL,author text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE templates(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),name text NOT NULL,kind text CHECK(kind IN('visual','structure','prompt')),fields jsonb NOT NULL DEFAULT '[]',locked jsonb NOT NULL DEFAULT '{}',example_version_id uuid REFERENCES versions(id),instructions text NOT NULL DEFAULT '',revision int NOT NULL DEFAULT 1,created_at timestamptz DEFAULT now());
CREATE TABLE template_versions(template_id uuid REFERENCES templates(id),revision int NOT NULL,snapshot jsonb NOT NULL,created_at timestamptz DEFAULT now(),PRIMARY KEY(template_id,revision));
ALTER TABLE publications ADD COLUMN campaign_id uuid REFERENCES campaigns(id);
ALTER TABLE publications ADD COLUMN tracking_url text NOT NULL DEFAULT '';
ALTER TABLE publications ADD COLUMN reminder_minutes int NOT NULL DEFAULT 60 CHECK(reminder_minutes BETWEEN 0 AND 10080);
CREATE TABLE measurements(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),publication_id uuid REFERENCES publications(id),measured_at timestamptz NOT NULL,mode text NOT NULL CHECK(mode IN('organic','paid')),views bigint NOT NULL DEFAULT 0 CHECK(views>=0),clicks bigint NOT NULL DEFAULT 0 CHECK(clicks>=0),likes bigint NOT NULL DEFAULT 0 CHECK(likes>=0),spend numeric NOT NULL DEFAULT 0 CHECK(spend>=0),currency text NOT NULL DEFAULT 'NOK',source text NOT NULL DEFAULT 'manual',UNIQUE(publication_id,measured_at,mode));
CREATE TABLE conversion_keys(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),token_hash text UNIQUE NOT NULL,revoked_at timestamptz,created_at timestamptz DEFAULT now());
CREATE TABLE conversions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),event_id text NOT NULL,order_id text NOT NULL DEFAULT '',payload_hash text NOT NULL,publication_id uuid REFERENCES publications(id),campaign_id uuid REFERENCES campaigns(id),kind text NOT NULL CHECK(kind IN('signup','purchase','refund')),amount numeric NOT NULL DEFAULT 0 CHECK(amount>=0),currency text NOT NULL DEFAULT 'NOK',occurred_at timestamptz NOT NULL,UNIQUE(product_id,event_id));
CREATE TABLE experiments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),campaign_id uuid REFERENCES campaigns(id),name text NOT NULL,hypothesis text NOT NULL,metric text NOT NULL DEFAULT 'conversions',variants uuid[] NOT NULL DEFAULT '{}',conclusion text NOT NULL DEFAULT '',knowledge_id uuid REFERENCES items(id),created_at timestamptz DEFAULT now());
CREATE TABLE claims(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),scope text NOT NULL CHECK(scope IN('platform','company','product')),statement text NOT NULL,sources jsonb NOT NULL DEFAULT '[]',confidence text NOT NULL CHECK(confidence IN('low','medium','high')),kind text NOT NULL DEFAULT 'claim' CHECK(kind IN('claim','customer_quote','objection')),contradicts uuid REFERENCES claims(id),resolved_at timestamptz,created_by text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),user_id uuid REFERENCES users(id),kind text NOT NULL,title text NOT NULL,entity_id text NOT NULL DEFAULT '',dedup text UNIQUE,read_by uuid[] NOT NULL DEFAULT '{}',created_at timestamptz DEFAULT now());
CREATE TABLE upload_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),actor_id text NOT NULL,title text NOT NULL,file_name text NOT NULL,body text NOT NULL DEFAULT '',rights text NOT NULL DEFAULT 'unknown',item_id uuid REFERENCES items(id),expected_version_id uuid REFERENCES versions(id),size bigint NOT NULL CHECK(size>0 AND size<=2147483648),offset_bytes bigint NOT NULL DEFAULT 0,file_key text NOT NULL,expires_at timestamptz NOT NULL DEFAULT now()+interval '2 days',completed_at timestamptz,result jsonb);
CREATE TABLE media_artifacts(version_id uuid REFERENCES versions(id),kind text NOT NULL,file_key text NOT NULL,mime text NOT NULL,PRIMARY KEY(version_id,kind));
CREATE TABLE segments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version_id uuid REFERENCES versions(id),start_seconds double precision NOT NULL DEFAULT 0 CHECK(start_seconds>=0),end_seconds double precision CHECK(end_seconds>=start_seconds),kind text NOT NULL CHECK(kind IN('speech','ocr','scene','hook','body','cta','broll','app')),body text NOT NULL,source text NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),version_id uuid REFERENCES versions(id),user_id uuid REFERENCES users(id),kind text NOT NULL,status text NOT NULL DEFAULT 'queued' CHECK(status IN('queued','running','completed','failed','cancelled','limited')),config jsonb NOT NULL DEFAULT '{}',input jsonb NOT NULL DEFAULT '{}',result jsonb NOT NULL DEFAULT '{}',progress text NOT NULL DEFAULT '',cost_usd numeric NOT NULL DEFAULT 0,created_at timestamptz DEFAULT now(),started_at timestamptz,finished_at timestamptz);
CREATE UNIQUE INDEX active_version_job ON jobs(version_id,kind) WHERE status IN('queued','running');
CREATE TABLE evaluations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version_id uuid REFERENCES versions(id),job_id uuid REFERENCES jobs(id),model text NOT NULL,criteria jsonb NOT NULL,context jsonb NOT NULL,result jsonb NOT NULL,cost_usd numeric NOT NULL,created_at timestamptz DEFAULT now());
CREATE TABLE search_documents(id text PRIMARY KEY,product_id uuid REFERENCES products(id),user_id uuid REFERENCES users(id),target_id text NOT NULL,version_id uuid REFERENCES versions(id),entity text NOT NULL,kind text NOT NULL,title text NOT NULL,body text NOT NULL,start_seconds double precision,status text NOT NULL,content_hash text NOT NULL,embedding double precision[],embedding_model text NOT NULL DEFAULT '',visual_embedding double precision[],search_vector tsvector GENERATED ALWAYS AS(to_tsvector('norwegian',title||' '||body)) STORED);
CREATE INDEX search_docs_fulltext ON search_documents USING gin(search_vector);
CREATE INDEX search_docs_product ON search_documents(product_id);
CREATE FUNCTION studio_cosine(a double precision[],b double precision[]) RETURNS double precision LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE AS $$ SELECT CASE WHEN array_length(a,1)<>array_length(b,1) THEN 0 ELSE coalesce(sum(x*y)/nullif(sqrt(sum(x*x)*sum(y*y)),0),0) END FROM unnest(a,b) AS v(x,y) $$;
CREATE TABLE model_profiles(product_id uuid REFERENCES products(id),role text NOT NULL,name text NOT NULL DEFAULT '',provider text NOT NULL,model text NOT NULL DEFAULT '',fallback_model text NOT NULL DEFAULT '',max_steps int NOT NULL CHECK(max_steps BETWEEN 1 AND 12),max_tokens int NOT NULL CHECK(max_tokens BETWEEN 128 AND 8192),timeout_seconds int NOT NULL CHECK(timeout_seconds BETWEEN 10 AND 300),max_cost_usd numeric NOT NULL CHECK(max_cost_usd>0 AND max_cost_usd<=5),PRIMARY KEY(product_id,role));
ALTER TABLE runs ADD COLUMN context_snapshot jsonb NOT NULL DEFAULT '{}';
ALTER TABLE runs ADD COLUMN partial text NOT NULL DEFAULT '';
ALTER TABLE runs ADD COLUMN fallback_model text NOT NULL DEFAULT '';
ALTER TABLE messages ADD COLUMN attachments uuid[] NOT NULL DEFAULT '{}';
CREATE TABLE workspace_limits(singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),storage_bytes bigint NOT NULL DEFAULT 21474836480 CHECK(storage_bytes>0),daily_ai_usd numeric NOT NULL DEFAULT 5 CHECK(daily_ai_usd>0),max_active_jobs int NOT NULL DEFAULT 20 CHECK(max_active_jobs BETWEEN 1 AND 100));
INSERT INTO workspace_limits(singleton) VALUES(true);
CREATE TABLE ai_ledger(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),product_id uuid REFERENCES products(id),operation text NOT NULL,reserved numeric NOT NULL,actual numeric,created_at timestamptz DEFAULT now());

ALTER TABLE tasks ADD COLUMN claim_started_at timestamptz;
CREATE TABLE agent_ratings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),version_id uuid REFERENCES versions(id),agent_id uuid REFERENCES agent_tokens(id),score double precision NOT NULL CHECK(score BETWEEN 0 AND 100),criteria text NOT NULL,model text NOT NULL,created_at timestamptz DEFAULT now());
