// Rewrite `src/lib/postcode-register.ts` from Bring's postcode register.
//
// The table is carried in the build rather than looked up while somebody lists
// a thing (see `src/lib/postcodes.ts`), so it goes stale when Bring opens,
// renames or closes a postcode — a few times a year, announced on
// bring.no/tjenester/adressetjenester/postnummer. Run this then, and commit
// what it writes.
//
//   pnpm postcodes
//
// The licence: bring.no publishes the file with no terms beside it, but Posten
// Bring AS (org. 984661185) has registered it in the national data catalogue,
// data.norge.no, as the dataset «Postnummer i Norge» under the Norwegian
// licence for Open Government data, NLOD 2.0. That allows copying,
// distributing and changing it, commercially too, on condition of the
// attribution NLOD § 5 words — the licensor, the licence, a link to both, and
// a note that we changed it. The header below carries it, and so does
// docs/DESIGN.md. Checked 26.09.2026; look again if the catalogue entry ever
// says otherwise.
import { writeFile } from 'node:fs/promises'

const SOURCE = 'https://www.bring.no/postnummerregister-ansi.txt'
// Where the licence is stated: the publisher's own entry in the national data
// catalogue, and the licence it names.
const CATALOGUE = 'https://data.norge.no/datasets/5e6847ba-156d-4e14-85d3-8d7f8b727523'
const LICENCE = 'https://data.norge.no/nlod/en/2.0'

/**
 * «MO I RANA» as it is written in a sentence: «Mo i Rana». Bring writes every
 * place in capitals, and a listing that shouts its town is not what 10b drew.
 * The small words are the only ones that stay small — «Vang på Hedmarken» —
 * and a lone letter after a name is a compass point, which stays a capital:
 * «Kristiansand S».
 */
function asWritten(place: string): string {
  return place
    .toLowerCase()
    .split(' ')
    .map((word, i) =>
      i > 0 && (word === 'i' || word === 'på')
        ? word
        : word
            .split('-')
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
            .join('-'),
    )
    .join(' ')
}

const response = await fetch(SOURCE)
if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}.`)

// «ansi» is ISO-8859-1, so Æ, Ø and Å are one byte each and not UTF-8.
const text = Buffer.from(await response.arrayBuffer()).toString('latin1')

const lines: string[] = []
for (const row of text.split(/\r?\n/)) {
  // Postcode, place, municipality number, municipality, kind of postcode.
  const [code, place] = row.split('\t')
  if (!code || !place) continue
  if (!/^\d{4}$/.test(code)) throw new Error(`Not a postcode: ${JSON.stringify(row)}`)
  // Written into a template literal below.
  if (/[`$\\]/.test(place)) throw new Error(`A place this file cannot hold: ${JSON.stringify(row)}`)
  lines.push(`${code} ${asWritten(place.trim())}`)
}
if (lines.length < 4000) throw new Error(`Only ${lines.length} postcodes; is ${SOURCE} still the register?`)

const fetched = new Date().toISOString().slice(0, 10)
const file = `// Generated by \`pnpm postcodes\` (src/db/postcodes.ts)
// from Bring's postcode register, ${SOURCE}, fetched ${fetched}.
// Do not edit by hand: run it again when Bring changes a postcode.
//
// Contains data under the Norwegian licence for Open Government data (NLOD)
// 2.0 distributed by Posten Bring AS: ${LICENCE}
// Source: ${CATALOGUE}
// Changed by Swaply: only the postcode and its place are kept, and the place
// is written as a sentence writes it rather than in capitals.
//
// One postcode per line, then the place it belongs to as a sentence writes it.
export const POSTCODE_REGISTER = \`
${lines.join('\n')}
\`
`

await writeFile(new URL('../lib/postcode-register.ts', import.meta.url), file)
console.log(`${lines.length} postcodes written to src/lib/postcode-register.ts.`)
