// Rewrite `src/lib/postcode-register.ts` from Bring's postcode register.
//
// The table is carried in the build rather than looked up while somebody lists
// a thing (see `src/lib/postcodes.ts`), so it goes stale when Bring opens,
// renames or closes a postcode — a few times a year, announced on
// bring.no/tjenester/adressetjenester/postnummer. Run this then, and commit
// what it writes.
//
//   pnpm postcodes
import { writeFile } from 'node:fs/promises'

const SOURCE = 'https://www.bring.no/postnummerregister-ansi.txt'

/**
 * «MO I RANA» as it is written in a sentence: «Mo i Rana». Bring writes every
 * place in capitals, and a listing that shouts its town is not what 10b drew.
 * The small words are the only ones that stay small — «Vang på Hedmarken» —
 * and a lone letter after a name is a compass point, which stays a capital:
 * «Kristiansand S».
 */
function asWritten(place: string): string {
  return place
    .toLowerCase()
    .split(' ')
    .map((word, i) =>
      i > 0 && (word === 'i' || word === 'på')
        ? word
        : word
            .split('-')
            .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
            .join('-'),
    )
    .join(' ')
}

const response = await fetch(SOURCE)
if (!response.ok) throw new Error(`${SOURCE} answered ${response.status}.`)

// «ansi» is ISO-8859-1, so Æ, Ø and Å are one byte each and not UTF-8.
const text = Buffer.from(await response.arrayBuffer()).toString('latin1')

const lines: string[] = []
for (const row of text.split(/\r?\n/)) {
  // Postcode, place, municipality number, municipality, kind of postcode.
  const [code, place] = row.split('\t')
  if (!code || !place) continue
  if (!/^\d{4}$/.test(code)) throw new Error(`Not a postcode: ${JSON.stringify(row)}`)
  // Written into a template literal below.
  if (/[`$\\]/.test(place)) throw new Error(`A place this file cannot hold: ${JSON.stringify(row)}`)
  lines.push(`${code} ${asWritten(place.trim())}`)
}
if (lines.length < 4000) throw new Error(`Only ${lines.length} postcodes; is ${SOURCE} still the register?`)

const fetched = new Date().toISOString().slice(0, 10)
const file = `// Generated by \`pnpm postcodes\` (src/db/postcodes.ts)
// from Bring's postcode register, ${SOURCE}, fetched ${fetched}.
// Do not edit by hand: run it again when Bring changes a postcode.
//
// One postcode per line, then the place it belongs to as a sentence writes it.
export const POSTCODE_REGISTER = \`
${lines.join('\n')}
\`
`

await writeFile(new URL('../lib/postcode-register.ts', import.meta.url), file)
console.log(`${lines.length} postcodes written to src/lib/postcode-register.ts.`)
